### ISSUE TITLE
Cards to-do

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/mahcards#2]
- [x] Add a field for a RE id
- [x] Convert Artfully field to ID only 
- [x] Work on the front-end interface, especially on the phone
- [ ] Surface tags and categories, as part of a "search" area
- [x] Check-in functionality

**Comment by halfempty** [comment]
Update fields to enable import:

- Inception to Date (or Year)
- Renewal to Date (or Month/Year)
- New Membership level field
